(cl:in-package #:gene-mangler.graph-data)


(defgeneric cut (mixer graph))
(defgeneric number-of-cuts (mixer))
(defgeneric connect-nodes (mixer a-node b-node))
(defgeneric nodes-connectable-p (mixer a-node b-node))
(defgeneric combine-fragments (mixer a-fragment b-fragment))
(defgeneric nodes (graph))
(defgeneric edges (object))
(defgeneric make-edge (mixer a-node b-node))
(defgeneric broken-edges (fragment))
(defgeneric follow-edge (origin edge))
(defgeneric original-edge (broken-edge))
(defgeneric (setf original-edge) (new-value broken-edge))
(defgeneric crawl (graph-object))
(defgeneric clone (graph-object))
(defgeneric first-node (edge))
(defgeneric (setf first-node) (new-value edge))
(defgeneric second-node (edge))
(defgeneric (setf second-node) (new-value edge))
(defgeneric break-cycles-p (mixer))
(defgeneric partakes-in-cycle-p (edge))
(defgeneric cycles (graph))
